### ISSUE TITLE
Makefile doesn't work on Windows

### ISSUE THREAD

**Issue by ghost** [fgken/find-music#1]
C:/Ruby193/lib/ruby/1.9.1/csv.rb:2058:in `=~': invalid byte sequence in Windows-
31J (ArgumentError)
        from C:/Ruby193/lib/ruby/1.9.1/csv.rb:2058:in`init_separators'
        from C:/Ruby193/lib/ruby/1.9.1/csv.rb:1590:in `initialize'
        from C:/Ruby193/lib/ruby/1.9.1/csv.rb:1349:in`new'
        from C:/Ruby193/lib/ruby/1.9.1/csv.rb:1349:in `open'
        from C:/Ruby193/lib/ruby/1.9.1/csv.rb:1411:in`read'
        from C:/Ruby193/lib/ruby/1.9.1/csv.rb:1427:in `table'
        from database/make_html.sjis.rb:5:in`<main>'

**Comment by fgken** [comment]
Use '-Eutf-8' option
